# Generated by Django 4.2.5 on 2023-09-09 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ranking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField(default=0)),
                ('uid', models.CharField(max_length=50)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('points', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='superuser',
            fields=[
                ('uid', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Tests',
            fields=[
                ('qid', models.IntegerField(primary_key=True, serialize=False)),
                ('show_type', models.CharField(max_length=15)),
                ('question', models.CharField(max_length=50)),
                ('opA', models.CharField(max_length=100, null=True)),
                ('opB', models.CharField(max_length=100, null=True)),
                ('opC', models.CharField(max_length=100, null=True)),
                ('opD', models.CharField(max_length=100, null=True)),
                ('opE', models.CharField(max_length=100, null=True)),
                ('ans', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User_ans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=50)),
                ('qid', models.IntegerField(default=0)),
                ('user_ans', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User_Info',
            fields=[
                ('uid', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('points', models.IntegerField(default=0)),
                ('now_state', models.CharField(default='default', max_length=255)),
            ],
        ),
    ]
